### ISSUE TITLE
[BSI][20200609] Duplicate Cookies with Missing Secure Flags

### ISSUE THREAD

**Issue by BSI-TF-CWA** [corona-warn-app/cwa-verification-iam#34]
Rating: Low
 
Description:
The server seems to issue some of its cookies twice with the term `_LEGACY`
appended. On these `_LEGACY` cookies the server does not set the secure flag.
If the `secure` flag is not set, the cookies will be transmitted in clear-text
when the user visits any HTTP URLs within the cookie's scope. An attacker may
be able to induce this event by feeding a user suitable links, either directly
or via another web site.

Additionally, the duplicate cookies should be removed.

Proof of Concept:
The following is a communication excerpt that shows the lack of the secure flag:

GET /auth/realms/cwa/login-actions/required-action?execution=update_user_locale&client_id=verification-portal&tab_id=[...] HTTP/1.1
Host: verification-iam-server
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:68.0) Gecko/20100101 Firefox/68.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Referer: https://verification-iam-server/auth/realms/cwa/login-actions/authenticate?execution=[...]&client_id=verification-portal&tab_id=[...]
Connection: close
Upgrade-Insecure-Requests: 1

HTTP/1.1 302 Found
Cache-Control: no-store, must-revalidate, max-age=0
Set-Cookie: KEYCLOAK_LOCALE=; Version=1; Comment=Expiring cookie; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Max-Age=0; Path=/auth/realms/cwa/; HttpOnly
Set-Cookie: KC_RESTART=; Version=1; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Max-Age=0; Path=/auth/realms/cwa/; HttpOnly
Set-Cookie: KEYCLOAK_IDENTITY=[REDACTED_VALUE_1]; Version=1; Path=/auth/realms/cwa/; SameSite=None; Secure; HttpOnly
Set-Cookie: KEYCLOAK_IDENTITY_LEGACY=[REDACTED_VALUE_1]; Version=1; Path=/auth/realms/cwa/; HttpOnly
Set-Cookie: KEYCLOAK_SESSION=[REDACTED_VALUE_2]; Version=1; Expires=Tue, 09-Jun-2020 04:13:38 GMT; Max-Age=36000; Path=/auth/realms/cwa/; SameSite=None; Secure
Set-Cookie: KEYCLOAK_SESSION_LEGACY=[REDACTED_VALUE_2]; Version=1; Expires=Tue, 09-Jun-2020 04:13:38 GMT; Max-Age=36000; Path=/auth/realms/cwa/
Set-Cookie: KEYCLOAK_REMEMBER_ME=; Version=1; Comment=Expiring cookie; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Max-Age=0; Path=/auth/realms/cwa/; HttpOnly
P3P: CP="This is not a P3P policy!"
X-XSS-Protection: 1; mode=block
Pragma: no-cache
Location: https://verification-portal-server/sso/login?state=[...]&session_state=[...]
Date: Mon, 08 Jun 2020 18:13:38 GMT
Connection: close
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Content-Type-Options: nosniff
Content-Length: 0

**Comment by thomasdarimont** [comment]
The LEGACY cookie variants are a workaround for older apple OSs whose browsers ignore cookies with SameSite=None
[Keycloak Commit](https://github.com/keycloak/keycloak/pull/6658/files#diff-7b4baca55e2613c16bc0a14fb25a51d6R75)
[Keycloak Issue KEYCLOAK-12125](https://issues.redhat.com/browse/KEYCLOAK-12125)

**Comment by haxxbard** [comment]
Planned for Version 1.0.x (17.07.2020)

**Comment by alstiefel** [comment]
This comment tries to wrap up the current analysis:

Problem Statement
P1 - the IAM duplicates certain cookies by adding  a "_legacy" suffix, it is not desirable to duplicate cookies
P2 - the duplicated cookies do not have a secure flag, so they might be transmitted in clear text

Analysis:
The reason for P1 is to support certain older apple OS (https://github.com/corona-warn-app/cwa-verification-iam/issues/34#issuecomment-645551543). The keycloak developers discuss different approaches which may be used in future releases.

P2 - although the cookies by themselfes do not require to transferred only via TLS. As the current configuration requires HSTS for requests, no browser interaction is done without TLS.

Proposal:
There are two option to react on the issue

A) Patch the existing keycloak application to remove the duplicate cookies until a future release will remove those cookies. The downside is that we would require to create a keycloak fork, which would mean we add additional time and effort to incorporate updates and hotfixes.

B) Wait until an updated version of keycloak will fix the issue.

Asssessment:
From our perspective it is not reasonable to fix the issue, because the fix would create a significant higher security risk than it fixes. We propose to "wont fix" this particular issue.

**Comment by alstiefel** [comment]
Is closes with wont fix as per communication with BSI

**Comment by floyd-fuh** [comment]
As keycloak now supports the "require SSL" setting in the realm login settings (which will turn on the Secure flag or rather not send the one without it), was this fixed?

**Comment by eldarj** [comment]
Problem Statement
P1 - the IAM duplicates certain cookies by adding a "_legacy" suffix, it is not desirable to duplicate cookies

What about the P1? Duplicating cookies is still not desirable.

This won't be taken into consideration? Is there any way we can set this as an optional feature, and allow some configuration, particularly allow removing them if that's what someone wants? They can be there by default.

In my case, I'm having issues with the size of these, as I have strict limitations for the size. Is there any approach really to remove these on a deployed server itself, through configuration, SPIs, etc.?
